### ISSUE TITLE
Create Session: flickering on button and form fields

### ISSUE THREAD

**Issue by may17** [coding-bootcamps-eu/questions-manager-class-august#110]
# Currently
When I focus and blur the input fields, there is some flicker effect. Also, the button looks strange after mouse down and release.
![Moo](https://drive.google.com/uc?export=view&id=1BtiYDDp8D10iGlQ7dAvvvP7p0XkOTg-X)

# Expected
There should be no flickering and the button should work like the others.

**Comment by NonoSikk** [comment]
fixxed ! Thanks 💯
